### ISSUE TITLE
2023.9b0 error on start up

### ISSUE THREAD

**Issue by icornish72** [jmcollin78/versatile_thermostat#100]
## Configuration

```yaml

Add your logs here.

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/versatile_thermostat/climate.py:21
Integration: versatile_thermostat (documentation, issues)
First occurred: 08:20:38 (1 occurrences)
Last logged: 08:20:38

Setup failed for custom integration versatile_thermostat: Unable to import component: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/versatile_thermostat/__init__.py", line 11, in <module>
    from .climate import VersatileThermostat
  File "/config/custom_components/versatile_thermostat/climate.py", line 21, in <module>
    from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)


## Describe the bug
Fails to start.


## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```

**Comment by jmcollin78** [comment]
Hello @icornish72 ,

What is your version of Home Assisstant ? I don't have any error with 2023.8.4.

**Comment by icornish72** [comment]
I am testing 2023.9b1

**Comment by jmcollin78** [comment]
I cannot support beta version yet because development environment is not available for beta version.
Thank you for the information, I will have to check when 2023.09 will be available.

**Comment by ingoratsdorf** [comment]
Hi.

I am now on Home Assistant 2023.9.0 and the error is still present.
Is there a fix for it?

**Comment by ingoratsdorf** [comment]
Looks like this happened in this HA committ:

Move DeviceInfo from entity to device registry (https://github.com/home-assistant/core/pull/98149)
https://github.com/home-assistant/core/commit/045c3279280e542ff1f082af166ab8949dd11a17

**Comment by ingoratsdorf** [comment]
The fix is trivial:

your file climate.py
#from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo

and your commons.py:
#from homeassistant.helpers.entity import Entity, DeviceInfo, DeviceEntryType
from homeassistant.helpers.entity import Entity
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo

**Comment by jmcollin78** [comment]
I will do a release this morning, thank you for the fix

**Comment by jmcollin78** [comment]
Fixed in release: https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.3.7
 Thanks to [ingoratsdorf](https://github.com/ingoratsdorf) for the quick fix.

**Comment by salaun29** [comment]
It's working well now, thanks !

**Comment by pcampan** [comment]
FYI - I'm good using chrome.  Appreciate the quick turnaround!
