### ISSUE TITLE
Erreur Journal suite MAJ HA en 2023.9

### ISSUE THREAD

**Issue by c7274864** [jmcollin78/versatile_thermostat#102]
Bonjour

Depuis la MAJ de HA une erreur s'affiche

`Logger: homeassistant.setup
Source: custom_components/versatile_thermostat/climate.py:21
Integration: versatile_thermostat ([documentation](https://github.com/jmcollin78/versatile_thermostat), [issues](https://github.com/jmcollin78/versatile_thermostat/issues))
First occurred: 22:58:21 (1 occurrences)
Last logged: 22:58:21

Setup failed for custom integration versatile_thermostat: Unable to import component: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/versatile_thermostat/__init__.py", line 11, in <module>
    from .climate import VersatileThermostat
  File "/config/custom_components/versatile_thermostat/climate.py", line 21, in <module>
    from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)`

**Comment by nicolinuxfr** [comment]
Même erreur, j'imagine que c'est lié aux modifications apportées par HA sur la gestion des thermostats.

```
Détails du journal (ERREUR)


 
Cette erreur provient d'une intégration personnalisée
Logger: homeassistant.setup
Source: custom_components/versatile_thermostat/climate.py:21
Integration: versatile_thermostat ([documentation](https://github.com/jmcollin78/versatile_thermostat), [issues](https://github.com/jmcollin78/versatile_thermostat/issues))
First occurred: 07:38:11 (1 occurrences)
Last logged: 07:38:11

Setup failed for custom integration versatile_thermostat: Unable to import component: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/versatile_thermostat/__init__.py", line 11, in <module>
    from .climate import VersatileThermostat
  File "/config/custom_components/versatile_thermostat/climate.py", line 21, in <module>
    from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```

**Comment by daangel27** [comment]
Hello,

Idem chez moi après update HA 2023.09. Comme l'indique @nicolinuxfr , ça semble lié aux modifs sur entity climate.
![image](https://github.com/jmcollin78/versatile_thermostat/assets/79531920/e5cd9256-05a5-42f4-94f7-3c9b672d61fc)

**Log:**
<img width="1182" alt="image" src="https://github.com/jmcollin78/versatile_thermostat/assets/79531920/854b575e-5533-47c7-a875-246ecca035cb">

**Comment by salaun29** [comment]
See https://github.com/jmco/versatile_thermostat/issues/100#issuecomment-1709256880

**Comment by c7274864** [comment]
@salaun29 
et en Français cela dis quoi ??
Un dev qui fait en Français c'est super,  avoir des solutions en anglais !!! , faudrait pensé a ceux qui ne savent pas lire et écrire en anglais , donc si tu es partant pour tout traduire la solution :-)

**Comment by nicolinuxfr** [comment]
C'est un correctif temporaire, mais j'imagine que l'auteur du projet corrigera rapidement. Pas de panique, il faut juste patienter un petit peu. 🙂

**Comment by jmcollin78** [comment]
Bonjour, je fais une release ce matin. Désolé, j'étais absent ces 2 derniers jours.

**Comment by jmcollin78** [comment]
Duplicate #100

**Comment by xekil** [comment]
hello, after update, same error

Edit : Logs

```
Logger: homeassistant.setup
Source: custom_components/versatile_thermostat/climate.py:21
Integration: Versatile Thermostat configuration ([documentation](https://github.com/jmcollin78/versatile_thermostat), [issues](https://github.com/jmcollin78/versatile_thermostat/issues))
First occurred: 08:04:59 (1 occurrences)
Last logged: 08:04:59

Setup failed for custom integration versatile_thermostat: Unable to import component: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/versatile_thermostat/__init__.py", line 11, in <module>
    from .climate import VersatileThermostat
  File "/config/custom_components/versatile_thermostat/climate.py", line 21, in <module>
    from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
ImportError: cannot import name 'DeviceEntryType' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)
```

**Comment by salaun29** [comment]
Works well on my side ...

**Comment by salaun29** [comment]
> @salaun29 et en Français cela dis quoi ?? Un dev qui fait en Français c'est super, avoir des solutions en anglais !!! , faudrait pensé a ceux qui ne savent pas lire et écrire en anglais , donc si tu es partant pour tout traduire la solution :-)


Dans le fichier climate.py remplacer :
#from homeassistant.helpers.entity import DeviceInfo, DeviceEntryType
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo

Dans le fichier commons.py remplacer :
#from homeassistant.helpers.entity import Entity, DeviceInfo, DeviceEntryType
from homeassistant.helpers.entity import Entity
from homeassistant.helpers.device_registry import DeviceEntryType, DeviceInfo

**Comment by xekil** [comment]
hello, after new update -> works well on my side  :)
