### ISSUE TITLE
[5.0.0] Config flow could not be loaded error when adding integration

### ISSUE THREAD

**Issue by maivorbim** [jmcollin78/versatile_thermostat#281]
Hello,

I am getting the following error on a fresh installation of the component via HACS, when I am trying to add the integration from HA Integrations page:

Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

There are no errors in HA log.

Versatile_thermostat verion: 5.0.0 installed via HACS
HA Core 2023.12.3
HA Supervisor 2023.11.6
HA Operating System 11.2

**Comment by apedance** [comment]
Same.

**Comment by jmcollin78** [comment]
Hello @maivorbim , @apedance ,

Yes this bug in a fresh installation have been reported. I will have a check this afternoon. Sorry for the inconvenience.

**Comment by jmcollin78** [comment]
Is the integration installed anyway ? If yes can you please restart HA a then try to Add a new Versatile Thermostat integration ? 
This could be a workaround (not tested).

**Comment by apedance** [comment]
Integration is installed via HACS. Did multiple restarts to make sure the addon is loaded.
Getting this error above.
How can we provide further logs?

**Comment by jmcollin78** [comment]
2023-12-18 13:41:23.133 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 880, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 898, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1006, in async_create_flow
    flow = handler()
           ^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/config_flow.py", line 602, in __init__
    super().__init__(dict())
  File "/config/custom_components/versatile_thermostat/config_flow.py", line 88, in __init__
    vtherm_api = VersatileThermostatAPI.get_vtherm_api()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 31, in get_vtherm_api
    if VersatileThermostatAPI._hass is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'VersatileThermostatAPI' has no attribute '_hass'

**Comment by apedance** [comment]
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1006, in async_create_flow
    flow = handler()
           ^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/config_flow.py", line 602, in __init__
    super().__init__(dict())
  File "/config/custom_components/versatile_thermostat/config_flow.py", line 88, in __init__
    vtherm_api = VersatileThermostatAPI.get_vtherm_api()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 31, in get_vtherm_api
    if VersatileThermostatAPI._hass is None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'VersatileThermostatAPI' has no attribute '_hass'

**Comment by B-Laurent** [comment]
Hello, 
I have the same error with a hacs installation on the following configuration  with the same log.
The release 430 could be installed but with graphical trouble (no text in dialog box). For the moment, no configuration has been made on this version.
If you need any help, don't hesitate to ask me, I'm capable of making a few attempts on my setup
Thank in advance for help.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.0.1

**Comment by maivorbim** [comment]
Works! Thanks for the quick fix!
