### ISSUE TITLE
Check- self_regulation_threshold - Possible regulation threshold issue

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#377]
### Discussed in https://github.com/jmcollin78/versatile_thermostat/discussions/375

<div type='discussions-op-text'>

<sup>Originally posted by **Edwintenhaaf** February  8, 2024</sup>
Hi All,

Before creating an issue I want to post it here to check  if the cause is related to versatile_thermostat.
Im using thermostat_over_climate to control three toshiba ac's.
I have configured the step size to 1 degree but I get these errors in the log.
The thermostat does not accept the temperatures because it only accepts rounded degrees.

the climate entities have the correct settings/attributes

min_temp: 15
max_temp: 30
target_temp_step: 1

Does any of you know what the problem can be ?

`Logger: homeassistant.core
Source: core.py:2295
First occurred: 12:55:56 PM (16 occurrences)
Last logged: 6:32:12 PM

Error executing service: <ServiceCall climate.set_temperature (c:01HP4SJ3PG5VS7ZXG7B6EGDC0C): entity_id=['climate.woonkamer_ac'], temperature=**25.2**, target_temp_high=30.0, target_temp_low=15.0>
Error executing service: <ServiceCall climate.set_temperature (c:01HP4SJ3PZ3G2VNK43WYFDSHNH): entity_id=['climate.overloop_ac'], temperature=**23.6**, target_temp_high=30.0, target_temp_low=15.0>
Error executing service: <ServiceCall climate.set_temperature (c:01HP4SW6Z0MKQ5FDDPJ7BT9Z38): entity_id=['climate.woonkamer_ac'], temperature=**24.27**, target_temp_high=30.0, target_temp_low=15.0>
Error executing service: <ServiceCall climate.set_temperature (c:01HP4V9BK46E101DWECWK7JPYN): entity_id=['climate.woonkamer_ac'], temperature=**23.01**, target_temp_high=30.0, target_temp_low=15.0>
Error executing service: <ServiceCall climate.set_temperature (c:01HP4WDW6J7C3SPG45PF77F0GB): entity_id=['climate.overloop_ac'], temperature=**23.8**, target_temp_high=30.0, target_temp_low=15.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2295, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 835, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/toshiba_ac/climate.py", line 112, in async_set_temperature
    await self._device.set_ac_temperature(set_temperature)
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/__init__.py", line 289, in set_ac_temperature
    state.ac_temperature = val
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/fcu_state.py", line 393, in ac_temperature
    self._ac_temperature = ToshibaAcFcuState.AcTemperature.to_raw(val)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/toshiba_ac/device/fcu_state.py", line 50, in to_raw
    return temp_to_raw[temperature]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 23.05

`

Thanks,

Edwin
</div>

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/5.4.2
