### ISSUE TITLE
Failure to initialize

### ISSUE THREAD

**Issue by kadaan** [jmcollin78/versatile_thermostat#39]
## Version of the custom_component
2.0.0beta7

## Configuration

```yaml

Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/climate.py", line 1073, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/climate.py", line 1766, in recalculate
    self.update_custom_attributes()
  File "/config/custom_components/versatile_thermostat/climate.py", line 1834, in update_custom_attributes
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 314, in state_attributes
    self.target_temperature_high,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 399, in target_temperature_high
    return self._attr_target_temperature_high
AttributeError: 'VersatileThermostat' object has no attribute '_attr_target_temperature_high'

```

## Describe the bug
Setup one thermostat over a climate device.  It tries to initialize, but fails part of the way through with the above error.

## Debug log

```text

Add your logs here.

```

**Comment by jmcollin78** [comment]
Fix commited in 2.0.0.beta8

**Comment by jmcollin78** [comment]
Hello @kadaan is that now ok with the beta 8 ?

I wanted to release the 2.0.0

**Comment by jmcollin78** [comment]
I will close the issue. Don't hesitate to reopen if it is not fixed
