### ISSUE TITLE
Entities unknown 

### ISSUE THREAD

**Issue by tbrasser** [jmcollin78/versatile_thermostat#443]
## Version of the custom_component

Latest 

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: []
min_temp: 15
max_temp: 25
target_temp_step: 0.5
current_temperature: null
temperature: null
icon: phu:aqara-thermo-e1
friendly_name: Badkamer
supported_features: 385

```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug

I'm trying to:

Donanything

And I expect:

But I observe this ....

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

Logger: homeassistant
Bron: components/climate/__init__.py:328
Eerst voorgekomen: 11:09:12 (2 gebeurtenissen)
Laatst gelogd: 11:09:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1460, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/thermostat_climate.py", line 552, in recalculate
    self.update_custom_attributes()
  File "/config/custom_components/versatile_thermostat/thermostat_climate.py", line 539, in update_custom_attributes
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1051, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 501, in capability_attributes
    data[ATTR_PRESET_MODES] = self.preset_modes
                              ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1141, in preset_modes
    return self._attr_preset_modes
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 328, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ThermostatOverClimate' object has no attribute '__attr_preset_modes'. Did you mean: '__attr_preset_mode'?

Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant
Bron: custom_components/versatile_thermostat/thermostat_climate.py:213
integratie: Versatile Thermostat (documentatie, problemen)
Eerst voorgekomen: 11:09:11 (1 gebeurtenissen)
Laatst gelogd: 11:09:11

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/__init__.py", line 109, in _async_startup_internal
    await api.init_vtherm_links()
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 178, in init_vtherm_links
    await entity.async_startup(self.find_central_configuration())
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 664, in async_startup
    await self.get_my_previous_state()
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 839, in get_my_previous_state
    await self._async_internal_set_temperature(
  File "/config/custom_components/versatile_thermostat/thermostat_climate.py", line 140, in _async_internal_set_temperature
    await self._send_regulated_temperature(force=True)
  File "/config/custom_components/versatile_thermostat/thermostat_climate.py", line 213, in _send_regulated_temperature
    and self.target_temperature > self.current_temperature
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'float' and 'NoneType'

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text

Add your logs here.

```

**Comment by jmcollin78** [comment]
Hello @tbrasser ,

Is it just at startup or still in normal use ? If it is only at startup this not a real problem and can be ignored.
Else it is a real issue that should not occurs.

**Comment by tbrasser** [comment]
I removed and reinstalled everything (including scrubbing .storage ) and now it seems to work pretty okay but there is still some bug with startup. I have to configure and modify 1 entry for everything to come up correctly.

I'm also seeing this behaviour with the custom integration `magic_areas` so I suspect a change in HA startup/loading/config/climate happened. 

It only seems to be not correct initially on vtherm-over-climate , my vtherm-over-switch is not showing the issue.

**Comment by jmcollin78** [comment]
Yes, with type `over_climate` VTherm need that the underlying climate is initialized. So there may be some temporary errors that could be ignored after the complete startup.
I will keep the issue open for a while, don't hesitate to add more info if needed

**Comment by tbrasser** [comment]
Just updated to your latest version and everything came up properly, will update here if anything strange happens again.

**Comment by tbrasser** [comment]
Well, now I cant set anything anymore...

![Screenshot_2024-04-16-14-06-58-947_io.homeassistant.companion.android.jpg](https://github.com/jmcollin78/versatile_thermostat/assets/2816560/0b37f6ce-79cd-4d94-858c-b3efc1be970e)

![Screenshot_2024-04-16-14-12-41-019_io.homeassistant.companion.android.jpg](https://github.com/jmcollin78/versatile_thermostat/assets/2816560/7a460fb4-7bb9-492b-9900-83d4404c708e)

Everytime I change something it resets to before

**Comment by jmcollin78** [comment]
Do you have logs ?

**Comment by tbrasser** [comment]
Actually those were the vtherm attributes :(


I downgraded to 6.1.0 and things work okay now.
