### ISSUE TITLE
In thermostat_over_climate mode, error when underlying climate is not available on startup

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#56]
Cf title.

At startup we have an error like this:

`VersatileThermostat-Thermostat chambre - Cannot find the underlying climate entity: climate.clim_chambre_parents_tuya. Thermostat will not be operational`

and then many errors like:
```
2023-02-28 08:21:05.484 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/climate.py", line 1540, in _async_climate_changed
    self.update_custom_attributes()
  File "/config/custom_components/versatile_thermostat/climate.py", line 2243, in update_custom_attributes
    ATTR_MEAN_POWER_CYCLE: self.mean_cycle_power,
  File "/config/custom_components/versatile_thermostat/climate.py", line 1008, in mean_cycle_power
    return float(self._device_power * self._prop_algorithm.on_percent)
AttributeError: 'NoneType' object has no attribute 'on_percent'
```

```
2023-02-28 08:21:05.612 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/climate.py", line 1319, in _async_ext_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/climate.py", line 2175, in recalculate
    self._prop_algorithm.calculate(
AttributeError: 'NoneType' object has no attribute 'calculate'
```

```
2023-02-28 08:25:00.817 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/climate.py", line 2049, in _async_control_heating
    on_time_sec: int = self._prop_algorithm.on_time_sec
AttributeError: 'NoneType' object has no attribute 'on_time_sec'
```

If not available, we should try to reconnect sometimes which is not the case.

**Comment by jmcollin78** [comment]
When underlying climate is not found the thermostat will try to discover it at each cycle.
So when the underlying climate reappears, the VThermostat restart automatically.
