### ISSUE TITLE
Action climate.set_preset_mode is not working on VTherm + Overkiz not compatible

### ISSUE THREAD

**Issue by Gandulf78** [jmcollin78/versatile_thermostat#617]
> Please read carefuly this instructions and fill this form before writing an issue. It helps me to help you.

## Version of the custom_component
v6.6.1

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes: auto, heat_cool
min_temp: 7
max_temp: 35
target_temp_step: 0.1
preset_modes: none, frost, eco, comfort, boost
current_temperature: 18.1
temperature: 18
hvac_action: heating
preset_mode: none
is_on: true
hvac_mode: heat_cool
type: null
is_controlled_by_central_mode: false
last_central_mode: null
frost_temp: 8
eco_temp: 16
boost_temp: 18
comfort_temp: 18
frost_away_temp: 8
eco_away_temp: 16
boost_away_temp: 18
comfort_away_temp: 16
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 8.6
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: eco
saved_target_temp: 18
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: input_boolean.any_presence
presence_state: on
window_state: off
window_auto_state: off
window_bypass_state: false
window_sensor_entity_id: null
window_delay_sec: null
window_auto_enabled: false
window_auto_open_threshold: null
window_auto_close_threshold: null
window_auto_max_duration: null
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: 2024-11-08T22:00:00.082010+01:00
last_ext_temperature_datetime: 2024-11-08T22:12:17.689335+01:00
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: null
total_energy: 32.19
last_update_datetime: 2024-11-08T22:17:13.629598+01:00
timezone: Europe/Paris
temperature_unit: °C
is_device_active: true
ema_temp: 18.2
is_used_by_central_boiler: false
temperature_slope: -0.34
hvac_off_reason: manual
is_over_climate: true
start_hvac_action_date: 2024-11-08T21:42:13.812980+01:00
underlying_entities: climate.hy_prog_therm
auto_fan_mode: auto_fan_high
current_auto_fan_mode: auto_fan_high
auto_activated_fan_mode: null
auto_deactivated_fan_mode: null
auto_regulation_use_device_temp: false
auto_start_stop_enable: false
auto_start_stop_level: auto_start_stop_none
auto_start_stop_dtmin: null
auto_start_stop_accumulated_error: 0
auto_start_stop_accumulated_error_threshold: null
friendly_name: Thermostat central HA
supported_features: 401
```

## If it is releveant to regulation performance or optimisation some curves are needed
To have a great curves demonstrating what you think is a problem, please install and configure what is described here: [Even better with Plotly to tune your Thermostat](#even-better-with-plotly-to-tune-your-thermostat)

## Describe the bug
I've got multiple errors on the logs related to my underlying Somfy thermostat (connected with Overkiz). It is not clear to me if the error is coming from Versatile Thermostat or Overkiz. The consequence is that sometimes the scheduler transition is missed.

I'm trying to:

And I expect:

But I observe this ....

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
logger:
    default: info
    logs:
        custom_components.versatile_thermostat: info
```

```text
2024-11-08 22:24:39.030 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat salle de sport HA - Underlying climate climate.i2g_actuator have changed. new_hvac_mode is off (vs None), new_hvac_action=None (vs None), new_target_temp=18.0 (vs None), new_fan_mode=None (vs None)
2024-11-08 22:24:39.031 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat salle de sport HA - Underlying climate.i2g_actuator is not initialized. Try to initialize it
2024-11-08 22:24:39.031 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Thermostat salle de sport HA-climate.i2g_actuator - The underlying climate entity: <entity climate.i2g_actuator=off> have been succesfully found
2024-11-08 22:24:39.031 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - Underlying climate climate.radiateur_electrique have changed. new_hvac_mode is heat (vs None), new_hvac_action=None (vs None), new_target_temp=16.0 (vs None), new_fan_mode=None (vs None)
2024-11-08 22:24:39.032 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - Underlying climate.radiateur_electrique is not initialized. Try to initialize it
2024-11-08 22:24:39.032 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Chambre Arthur-climate.radiateur_electrique - The underlying climate entity: <entity climate.radiateur_electrique=heat> have been succesfully found
2024-11-08 22:24:39.032 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
2024-11-08 22:24:39.032 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - Underlying climate climate.hy_prog_therm have changed. new_hvac_mode is heat_cool (vs None), new_hvac_action=heating (vs None), new_target_temp=18.0 (vs None), new_fan_mode=None (vs None)
2024-11-08 22:24:39.032 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - underlying just switch ON. Set power and energy start date 2024-11-08T22:24:38.990035+01:00
2024-11-08 22:24:39.033 INFO (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - Underlying climate.hy_prog_therm is not initialized. Try to initialize it
2024-11-08 22:24:39.033 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Thermostat central HA-climate.hy_prog_therm - The underlying climate entity: <entity climate.hy_prog_therm=heat_cool> have been succesfully found
2024-11-08 22:24:39.033 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
2024-11-08 22:24:39.034 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Thermostat salle de sport HA - The config entry have been updated
2024-11-08 22:24:39.036 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Chambre Arthur - The config entry have been updated
2024-11-08 22:24:39.037 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
2024-11-08 22:24:39.038 INFO (MainThread) [custom_components.versatile_thermostat.base_thermostat] VersatileThermostat-Thermostat central HA - The config entry have been updated
2024-11-08 22:24:39.039 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
2024-11-08 22:24:39.114 INFO (MainThread) [homeassistant.setup] Setting up media_player
2024-11-08 22:24:39.122 INFO (MainThread) [homeassistant.setup] Setup of domain media_player took 0.01 seconds
2024-11-08 22:24:39.122 INFO (MainThread) [homeassistant.components.media_player] Setting up apple_tv.media_player
2024-11-08 22:24:39.127 INFO (MainThread) [homeassistant.setup] Setting up remote
2024-11-08 22:24:39.129 INFO (MainThread) [homeassistant.setup] Setup of domain remote took 0.00 seconds
2024-11-08 22:24:39.129 INFO (MainThread) [homeassistant.components.remote] Setting up apple_tv.remote
2024-11-08 22:24:39.268 INFO (MainThread) [homeassistant.components.sensor] Setting up rest.sensor
2024-11-08 22:24:39.269 INFO (MainThread) [homeassistant.components.sensor] Setting up rest.sensor
2024-11-08 22:24:39.270 INFO (MainThread) [homeassistant.components.sensor] Setting up rest.sensor
2024-11-08 22:24:39.316 INFO (MainThread) [homeassistant.setup] Setting up template
2024-11-08 22:24:39.317 INFO (MainThread) [homeassistant.setup] Setup of domain template took 0.00 seconds
2024-11-08 22:24:39.317 INFO (MainThread) [homeassistant.components.sensor] Setting up template.sensor
2024-11-08 22:24:39.320 INFO (MainThread) [homeassistant.components.sensor] Setting up template.sensor
2024-11-08 22:24:39.322 INFO (MainThread) [homeassistant.components.switch] Setting up template.switch
2024-11-08 22:24:39.324 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up template.binary_sensor
2024-11-08 22:24:39.326 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up template.binary_sensor
2024-11-08 22:24:39.327 INFO (MainThread) [homeassistant.components.sensor] Setting up template.sensor
2024-11-08 22:24:39.328 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.meteofrance_forecast_temperature (<class 'homeassistant.components.template.sensor.TriggerSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['K', '°F', '°C']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
2024-11-08 22:24:39.328 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.meteofrance_forecast_humidity (<class 'homeassistant.components.template.sensor.TriggerSensorEntity'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+template%22
2024-11-08 22:24:39.615 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up workday.binary_sensor
2024-11-08 22:24:39.621 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_preset_mode (c:01JC6TME245A19WR8BBHA9J2DP): preset_mode=eco, entity_id=['climate.thermostat_chambre_arthur_ha']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 799, in async_handle_set_preset_mode_service
    self._valid_mode_or_raise("preset", preset_mode, self.preset_modes)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 727, in _valid_mode_or_raise
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: not_valid_preset_mode

2024-11-08 22:24:40.694 INFO (MainThread) [custom_components.versatile_thermostat.underlyings] VersatileThermostat-Thermostat central HA-climate.hy_prog_therm - The hvac mode is OFF, but the underlying device is ON. Turning off device climate.hy_prog_therm
2024-11-08 22:24:40.695 WARNING (MainThread) [homeassistant.components.climate] overkiz::SomfyHeatingTemperatureInterface sets the hvac_mode off which is not valid for this entity with modes: auto, heat_cool. This will stop working in 2025.4 and raise an error instead. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+overkiz%22
2024-11-08 22:24:40.695 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_hvac_mode (c:01JC6TMF3PG2527R08T52K7T86): entity_id=['climate.hy_prog_therm'], hvac_mode=off>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 772, in async_handle_set_hvac_mode_service
    await self.async_set_hvac_mode(hvac_mode)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/overkiz/climate/somfy_heating_temperature_interface.py", line 115, in async_set_hvac_mode
    OverkizCommand.SET_ACTIVE_MODE, HVAC_MODES_TO_OVERKIZ[hvac_mode]
                                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: <HVACMode.OFF: 'off'>

```

**Comment by jmcollin78** [comment]
Hello @Gandulf78 

> v3.3.7

Tnis is not a Versatile Thermostat release or you are very outdated. The last release is 6.6.1

> homeassistant.exceptions.ServiceValidationError: not_valid_preset_mode

Is that the VTherm entityId `climate.thermostat_chambre_arthur_ha` or the overkiz ?

I think you try to call the service directly ?

```
action: climate.set_preset_mode
target:
  entity_id: climate.clim_chambre
data:
  preset_mode: eco
```

This generate no error on my side, but the VTherm didn't change to Eco preset. It seems the action `climate.set_preset_mode` is no more working on Vtherm.

> OverkizCommand.SET_ACTIVE_MODE, HVAC_MODES_TO_OVERKIZ[hvac_mode]

The error message is clear. Overkiz doesn't support to be turned off (hvac_off). This will be difficult to use with VTherm then. In a general manner, Overkiz is an old and not maintained integration. It is cloud based an not reliable. I'm sorry but you will have problem if it doesn't respect a minimal specification. hvac_off is mandatory for Vtherm (window detection turns off, auto-start/stop uses also off, on/off buttons from UI will not work).

**Comment by Gandulf78** [comment]
> Hello @Gandulf78
> 
> > v3.3.7
> 
> Tnis is not a Versatile Thermostat release or you are very outdated. The last release is 6.6.1

Sorry, it is 6.6.1.

> 
> > homeassistant.exceptions.ServiceValidationError: not_valid_preset_mode
> 
> Is that the VTherm entityId `climate.thermostat_chambre_arthur_ha` or the overkiz ?

it is the Therm entityId, the underlying overkiz is climate.thermostat_chambre_arthur

> 
> I think you try to call the service directly ?
> 
> ```
> action: climate.set_preset_mode
> target:
>   entity_id: climate.clim_chambre
> data:
>   preset_mode: eco
> ```
> 

No but I need to dig into it. 

> This generate no error on my side, but the VTherm didn't change to Eco preset. It seems the action `climate.set_preset_mode` is no more working on Vtherm.
> 
> > OverkizCommand.SET_ACTIVE_MODE, HVAC_MODES_TO_OVERKIZ[hvac_mode]
> 
> The error message is clear. Overkiz doesn't support to be turned off (hvac_off). This will be difficult to use with VTherm then. In a general manner, Overkiz is an old and not maintained integration. It is cloud based an not reliable. I'm sorry but you will have problem if it doesn't respect a minimal specification. hvac_off is mandatory for Vtherm (window detection turns off, auto-start/stop uses also off, on/off buttons from UI will not work).

I disagree. Overkiz is still maintained and part of HA core. I have also created a ticket to them.
I agree that it is cloud based (even though there's a local API but unfortunately not working for climate).
Regarding the minimum specifications,  window detection is only optional and could be handle by reducing the temperature. I don't mind actually to not be able to shut off the thermostat from UI actually (I removed the button). I love the principle of your integration allowing to reduce easily the temperature by taking into account the presence detection. 
Could you maybe please consider to propose workarounds for this case ? Thank you.

**Comment by jmcollin78** [comment]
Hello @Gandulf78 ,

I will fix the set_preset_mode action which is not working in VTherm but of course, I cannot fix the Overkiz which don't implement the HVAC_OFF. So I don't know exactly how VTherm will behave without it but you will have to try and don't use feature that can turn-off/on the VTherm.

For my knowledge how do you turn off your heaters if there is no HVAC_OFF supported ?

**Comment by Gandulf78** [comment]
Thanks a lot for this. I can turn off my radiators and thermostat from Tahoma app. It is a shame that the Overkiz integration is incomplete.

**Comment by jmcollin78** [comment]
Finally after some tests it is working fine:
1. before 'comfort'
![Capture d’écran 2024-11-10 à 11 23 08](https://github.com/user-attachments/assets/d8144180-4519-4e93-82b4-c0ac473741d6)
2. calling action set_preset_mode to eco:
![Capture d’écran 2024-11-10 à 11 23 41](https://github.com/user-attachments/assets/f30dd767-3892-42da-b84c-ea07c33cea55)
3. the havc_mode is now 'eco'
![Capture d’écran 2024-11-10 à 11 24 22](https://github.com/user-attachments/assets/a11ab2b3-41b4-49a2-be40-04beef651c67)
4. select 'comfort' preset
![Capture d’écran 2024-11-10 à 11 24 58](https://github.com/user-attachments/assets/6beae0bc-c112-48eb-a495-a218df86f35d)
5. the VTherm is now in Comfort
![Capture d’écran 2024-11-10 à 11 25 32](https://github.com/user-attachments/assets/e1e27b7a-b03a-46eb-a9c8-76ad5e247007)

Can you please do exactly the same steps and see if it works ?

Note: I am with the 6.6.3.beta release at home.

**Comment by Gandulf78** [comment]
Hi. 
So i installed the 6.6.3.beta1.

First mode confort (14h01):
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 01 35" src="https://github.com/user-attachments/assets/46597b81-6984-4fc2-a303-794275735bff">
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 01 57" src="https://github.com/user-attachments/assets/b5c59b85-a0c9-4e10-b12b-9765444b5e85">

Then select mode eco (14h05):
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 05 26" src="https://github.com/user-attachments/assets/99f69150-1279-4419-be26-d49b09787713">
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 05 34" src="https://github.com/user-attachments/assets/24b0334b-5834-4e21-ab6d-416b1dc38337">

error message in the logs at the same time:
2024-11-10 14:05:44.381 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_temperature (c:01JCB2WADWS4V7ZWP9HRP2NXVZ): entity_id=['climate.hy_prog_therm'], temperature=18.0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 1029, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/overkiz/climate/somfy_heating_temperature_interface.py", line 185, in async_set_temperature
    SETPOINT_MODE_TO_OVERKIZ_COMMAND[mode.value_as_str], temperature
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'free'

Reselect comfort mode:
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 06 17" src="https://github.com/user-attachments/assets/0b92bfd1-2a98-432b-a118
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 06 27" src="https://github.com/user-attachments/assets/74104f92-ef23-456e-8403-f011f68006e4">
-f7d2ebef15ae">

No error message.

I also noticed the suspicious transitions in the logs:
<img width="1678" alt="Capture d’écran 2024-11-10 à 14 15 16" src=
<img width="2048" alt="Capture d’écran 2024-11-10 à 14 12 31" src="https://github.com/user-attachments/assets/46692f38-e925-43a4-8d14-8b5ad6a6e210">
"https://github.com/user-attachments/assets/e378e8c6-86cd-4bab-aba7-b162a50398d0">

I am wondering if it is HomeKit which is triggering these events. I will remove the Climate to Homebridge to see what happens.

**Comment by Gandulf78** [comment]
After removing Climate from Homebridge and restarting HA, I have so far only the following error messages (climate.hy_prog_therm is my underlying Overkiz central thermostat, climate.thermostat_central_ha is my Versatile thermostat scheduled by Scheduler):
[home-assistant_2024-11-10T13-54-13.653Z.log](https://github.com/user-attachments/files/17691653/home-assistant_2024-11-10T13-54-13.653Z.log)

According to the scheduler, at this time the Versatile Thermostat should be in "comfort" preset.

**Comment by jmcollin78** [comment]
Instead of doing screen copy, you just have to select the VTherm and copy/past all attributes in the top window.
You paste it and put the <> to indicate this is code. This is much more efficient.

**Comment by jmcollin78** [comment]
```
2024-11-10 14:05:44.381 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_temperature (c:01JCB2WADWS4V7ZWP9HRP2NXVZ): entity_id=['climate.hy_prog_therm'], temperature=18.0>
```

this indicates that VTherm was not able to change the target temperature on the Overkiz thermostat.

So sad for you, you cannot stop the thermostat and you cannot change the temperature also.

I will close this issue because, there is nothing I can do for you. This system is not compatible.

**Comment by Gandulf78** [comment]
Sorry but usually (99% of the time) it works and Versatile Thermostat is able to change the target temperature. Maybe it is because it is an initialization issue (underlying not ready).

**Comment by Gandulf78** [comment]
I am curious about this part in the logs which seems to be directly related to Versatile Thermostat (comfort mode not valid?):

**2024-11-10 14:22:16.948 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.**
2024-11-10 14:22:16.953 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
**2024-11-10 14:22:16.955 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Thermostat central HA - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.**
2024-11-10 14:22:17.065 WARNING (MainThread) [custom_components.versatile_thermostat.thermostat_climate] VersatileThermostat-Chambre Arthur - don't send regulated temperature cause VTherm target_temp (None) is None. This should be a temporary warning message.
**2024-11-10 14:22:17.067 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_preset_mode (c:01JCB3TKVB700VTV7BS16H50SK): preset_mode=comfort, entity_id=['climate.thermostat_central_ha']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/local/lib/python3.12/site-packages/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 799, in async_handle_set_preset_mode_service
    self._valid_mode_or_raise("preset", preset_mode, self.preset_modes)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/climate/__init__.py", line 727, in _valid_mode_or_raise
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: not_valid_preset_mode**

**Comment by Gandulf78** [comment]
> ok that is possible indeed. That could be the case with cloud based integration. If the cloud is not available at restart, you could have this error.
> 
> I can suggest two things anymway:
> 
> 1. remove all electronics of your heater and simply control it via a switch (example: AQARA T1, Sonoff Zigbee  module, Nodon, ...). Then you will be able to work directly without any cloud with HA and VTherm. That is what I have done 2 years ago, and I don't regret my choice,
> 2. post the error messages in the community or in the core github (issues). I known there is many, many issues not resolved but you will maybe have an answer.

Actually I cannot. My main thermostat is handling a gas boiler. And my two additional "smart" electrical radiators are connected to Tahoma.

**Comment by Gandulf78** [comment]
Ok finally I sorted it out. I completely removed Versatile Thermostat and use the Overkiz directly. I manage to intercept orders from the scheduler and change temperatures with automations. I only use in the scheduler the presets supported by my radiators and central thermostat. 
It was a lot of work but everything is working without error and so far so good. 
It is a shame Somfy integration is so poorly implemented. 
Thanks anyway to help me to figure out where the issue was.

**Comment by jmcollin78** [comment]
You are welcome.
