### ISSUE TITLE
problème suite mise a jour homeassistant 

### ISSUE THREAD

**Issue by Maabou08** [jmcollin78/versatile_thermostat#706]
Bonjour, 

plus rien de fonctionner avec l'intégration Daikin
voici le message dans le journal de homeassistant 

Enregistreur: homeassistant.config_entries
Source: config_entries.py:640
S'est produit pour la première fois: 19:52:12 (3 occurrences)
Dernier enregistrement: 19:52:22

Error setting up entry Thermostat Chambre Gaëtan for versatile_thermostat
Error setting up entry Thermostat Salle à manger for versatile_thermostat
Error setting up entry Thermostat Chambre Max for versatile_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/__init__.py", line 183, in async_setup_entry
    await api.init_vtherm_links(entry.entry_id)
  File "/config/custom_components/versatile_thermostat/vtherm_api.py", line 189, in init_vtherm_links
    await entity.async_startup(self.find_central_configuration())
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 737, in async_startup
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^l' 
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 2702, in async_write_ha_state
    return super().async_write_ha_state()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1081, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 530, in capability_attributes
    data[ATTR_SWING_HORIZONTAL_MODES] = self.swing_horizontal_modes
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "src/propcache/_helpers_c.pyx", line 80, in propcache._helpers_c.cached_property.__get__
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 727, in swing_horizontal_modes
    return self._attr_swing_horizontal_modes
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 337, in __getattribute__
    return super().__getattribute__(name)
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
AttributeError: 'ThermostatOverClimate' object has no attribute '__attr_swing_horizontal_modes'. Did you mean: '_attr_swing_horizontal_modes'?

**Comment by jmcollin78** [comment]
Seems duplicate of https://github.com/jmcollin78/versatile_thermostat/issues/702
