### ISSUE TITLE
Issue with over_valve and Shelly TRVs

### ISSUE THREAD

**Issue by dd310** [jmcollin78/versatile_thermostat#721]
## Version of the custom_component

`6.8.3`

## Configuration

My VTherm attributes are the following:
```yaml
hvac_modes:
  - heat
  - "off"
min_temp: 7
max_temp: 25
target_temp_step: 0.1
current_temperature: 21
temperature: 20.5
hvac_action: idle
friendly_name: Bagno
supported_features: 401
is_on: true
hvac_mode: heat
preset_mode: comfort
type: null
is_controlled_by_central_mode: true
last_central_mode: Heat only
frost_temp: 7
eco_temp: 7
boost_temp: 7
comfort_temp: 20.5
frost_away_temp: 0
eco_away_temp: 0
boost_away_temp: 0
comfort_away_temp: 0
power_temp: null
target_temperature_step: 0.1
ext_current_temperature: 11.96
ac_mode: false
current_power: null
current_power_max: null
saved_preset_mode: comfort
saved_target_temp: 20.5
saved_hvac_mode: null
motion_sensor_entity_id: null
motion_state: null
power_sensor_entity_id: null
max_power_sensor_entity_id: null
overpowering_state: null
presence_sensor_entity_id: null
presence_state: null
window_state: "off"
window_auto_state: "off"
window_bypass_state: false
window_sensor_entity_id: binary_sensor.finestra_bagno_apertura
window_delay_sec: 30
window_auto_enabled: false
window_auto_open_threshold: 3
window_auto_close_threshold: 0
window_auto_max_duration: 30
window_action: window_turn_off
security_delay_min: 60
security_min_on_percent: 0.5
security_default_on_percent: 0.1
last_temperature_datetime: "2024-12-19T20:08:46.047959+01:00"
last_ext_temperature_datetime: "2024-12-19T20:08:11.737351+01:00"
security_state: false
minimal_activation_delay_sec: 10
device_power: 1
mean_cycle_power: 0
total_energy: 0
last_update_datetime: "2024-12-19T20:13:03.905540+01:00"
timezone: Europe/Rome
temperature_unit: °C
is_device_active: false
nb_device_actives: 0
ema_temp: 21
is_used_by_central_boiler: false
temperature_slope: 0
hvac_off_reason: null
max_on_percent: null
have_valve_regulation: false
valve_open_percent: 0
is_over_valve: true
underlying_entities:
  - number.termosifone_bagno_valve_position
on_percent: 0
on_time_sec: 0
off_time_sec: 300
cycle_min: 5
function: tpi
tpi_coef_int: 0.6
tpi_coef_ext: 0.01
auto_regulation_dpercent: 10
auto_regulation_period_min: 5
last_calculation_timestamp: null
calculated_on_percent: 0
preset_modes:
  - none
  - frost
  - eco
  - comfort
  - boost
```

## Describe the bug

When starting/restarting Home Assistant, randomly the error in the log below pops up and the adjustment cycle of the valve position hangs.
What I think is happening is that sometimes Versatile Thermostats loads before the Shelly integrations has finished loading. 

Would it be possible to implement some kind of check so that, if the shelly default climate.* entity (or the number.* entity itself) is unavailable, the command is not sent? Just my two cents, I don't know which approach would be viable.

Thanks

I read the documentation on the README.md file and I don't find any relevant information about this issue.

## Debug log

```yaml
Registratore: homeassistant.core
Fonte: core.py:2822
Prima occorrenza: 20:08:04 (1 occorrenze)
Ultimo accesso: 20:08:04

Error executing service: <ServiceCall number.set_value (c:01JFG53SPC7V1XG9VT1ASQS3M5): value=0.0, entity_id=['number.termosifone_bagno_valve_position']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/usr/src/homeassistant/homeassistant/components/shelly/number.py", line 174, in async_set_native_value
    await self._set_state_full_path(
    ...<2 lines>...
    )
  File "/usr/src/homeassistant/homeassistant/components/shelly/number.py", line 184, in _set_state_full_path
    return await self.coordinator.device.http_request("get", path, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/block_device/device.py", line 313, in http_request
    if self.options.auth is None and self.requires_auth:
                                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/block_device/device.py", line 407, in requires_auth
    if "auth" not in self.shelly:
                     ^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioshelly/block_device/device.py", line 438, in shelly
    raise NotInitialized
aioshelly.exceptions.NotInitialized
```

**Comment by jmcollin78** [comment]
Hello, the issue is in the Shelly integration. It seems that it can't authenticate. Please open an issue in Shelly github.
