### ISSUE TITLE
Bug sur mise en sécurité quand last_temp_date > au seuil défini

### ISSUE THREAD

**Issue by jmcollin78** [jmcollin78/versatile_thermostat#81]
When a Thermostat should go to security mode because temperature is not received, this could failed.
See error logs :

```log
2023-04-26 06:04:15.976 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/logging/handlers.py", line 1475, in emit
self.enqueue(self.prepare(record))
File "/usr/src/homeassistant/homeassistant/util/logging.py", line 44, in prepare
record = super().prepare(record)
File "/usr/local/lib/python3.10/logging/handlers.py", line 1457, in prepare
msg = self.format(record)
File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
return fmt.format(record)
File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
record.message = record.getMessage()
File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
msg = msg % self.args
RecursionError: maximum recursion depth exceeded
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/versatile_thermostat/climate.py", line 1391, in _async_temperature_changed
await self._async_control_heating(force=False)
File "/config/custom_components/versatile_thermostat/climate.py", line 2218, in _async_control_heating
security: bool = await self.check_security()
File "/config/custom_components/versatile_thermostat/climate.py", line 2130, in check_security
await self.async_set_hvac_mode(HVACMode.OFF)
File "/config/custom_components/versatile_thermostat/climate.py", line 1211, in async_set_hvac_mode
await self._async_control_heating(force=True)
File "/config/custom_components/versatile_thermostat/climate.py", line 2218, in _async_control_heating
security: bool = await self.check_security()
File "/config/custom_components/versatile_thermostat/climate.py", line 2164, in check_security
await self.restore_hvac_mode()
File "/config/custom_components/versatile_thermostat/climate.py", line 1958, in restore_hvac_mode
await self.async_set_hvac_mode(self._saved_hvac_mode)
File "/config/custom_components/versatile_thermostat/climate.py", line 1211, in async_set_hvac_mode
await self._async_control_heating(force=True)
File "/config/custom_components/versatile_thermostat/climate.py", line 2218, in _async_control_heating
security: bool = await self.check_security()
File "/config/custom_components/versatile_thermostat/climate.py", line 2130, in check_security
await self.async_set_hvac_mode(HVACMode.OFF)
File "/config/custom_components/versatile_thermostat/climate.py", line 1211, in async_set_hvac_mode
await self._async_control_heating(force=True)
File "/config/custom_components/versatile_thermostat/climate.py", line 2218, in _async_control_heating
security: bool = await self.check_security()
```

```log
2023-04-26 06:04:14.436 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - No temperature received for more than 180.0 minutes (dt=310.7, dext=4.2) and on_percent (0.54) is over defined value (0.25). Set it into security mode
2023-04-26 06:04:14.454 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - End of security mode. restoring hvac_mode to heat and preset_mode to comfort
2023-04-26 06:04:14.458 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - No temperature received for more than 180.0 minutes (dt=310.7, dext=4.2) and on_percent (0.54) is over defined value (0.25). Set it into security mode
2023-04-26 06:04:14.460 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - End of security mode. restoring hvac_mode to heat and preset_mode to comfort
2023-04-26 06:04:14.462 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - No temperature received for more than 180.0 minutes (dt=310.7, dext=4.2) and on_percent (0.54) is over defined value (0.25). Set it into security mode
2023-04-26 06:04:14.464 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - End of security mode. restoring hvac_mode to heat and preset_mode to comfort
2023-04-26 06:04:14.466 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - No temperature received for more than 180.0 minutes (dt=310.7, dext=4.2) and on_percent (0.54) is over defined value (0.25). Set it into security mode
2023-04-26 06:04:14.468 WARNING (MainThread) [custom_components.versatile_thermostat.climate] VersatileThermostat-Thermostat Salle de bain RDC - End of security mode. restoring hvac_mode to heat and preset_mode to comfort
```

**Comment by armellarcier** [comment]
Hi! I just encountered something similar on 8.1.0 after a target temp set (triggered by planner)

```python
Error executing script. Unexpected error for call_service at pos 3: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/logging/handlers.py", line 1509, in emit
    self.enqueue(self.prepare(record))
                 ~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/handlers.py", line 1491, in prepare
    msg = self.format(record)
  File "/usr/local/lib/python3.13/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 712, in format
    record.message = record.getMessage()
                     ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 524, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1009, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2816, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2859, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 830, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 902, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 828, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1248, in async_set_temperature
    await self.update_states(force=True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1332, in update_states
    await self.async_control_heating(force=force or sub_need_control_heating)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1372, in async_control_heating
    if await self._safety_manager.refresh_and_update_if_changed():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 245, in refresh_and_update_if_changed
    await self._vtherm.update_states(force=True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1332, in update_states
    await self.async_control_heating(force=force or sub_need_control_heating)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1372, in async_control_heating
    if await self._safety_manager.refresh_and_update_if_changed():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 245, in refresh_and_update_if_changed
    await self._vtherm.update_states(force=True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1332, in update_states
    await self.async_control_heating(force=force or sub_need_control_heating)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1372, in async_control_heating
    if await self._safety_manager.refresh_and_update_if_changed():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 245, in refresh_and_update_if_changed
    await self._vtherm.update_states(force=True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1332, in update_states
    await self.async_control_heating(force=force or sub_need_control_heating)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1372, in async_control_heating
    if await self._safety_manager.refresh_and_update_if_changed():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 245, in refresh_and_update_if_changed
    await self._vtherm.update_states(force=True)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1332, in update_states
    await self.async_control_heating(force=force or sub_need_control_heating)
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1372, in async_control_heating
    if await self._safety_manager.refresh_and_update_if_changed():
```
`[...]`
```python

    if await self._safety_manager.refresh_and_update_if_changed():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 243, in refresh_and_update_if_changed
    if old_safety != await self.refresh_state():
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/feature_safety_manager.py", line 178, in refresh_state
    self._vtherm.send_event(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        EventType.TEMPERATURE_EVENT,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        },
        ^^
    )
    ^
  File "/config/custom_components/versatile_thermostat/base_thermostat.py", line 1620, in send_event
    send_vtherm_event(self._hass, event_type=event_type, entity=self, data=data)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/const.py", line 516, in send_vtherm_event
    _LOGGER.info("%s - Sending event %s with data: %s", entity, event_type, data)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1520, in info
    self._log(INFO, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1665, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1681, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1737, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 113, in handle
    self.emit(record)
    ~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/handlers.py", line 1511, in emit
    self.handleError(record)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/logging/__init__.py", line 1076, in handleError
    traceback.print_exception(exc, limit=None, file=sys.stderr)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/traceback.py", line 129, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
  File "/usr/local/lib/python3.13/traceback.py", line 1052, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _walk_tb_with_full_positions(exc_traceback),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        limit=limit, lookup_lines=lookup_lines,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        capture_locals=capture_locals)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/traceback.py", line 476, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
                                                     ^^^^^^^^^
  File "/usr/local/lib/python3.13/traceback.py", line 408, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
RecursionError: maximum recursion depth exceeded
```

It seems possible to loop between base_thermostat and feature_safety_manager.

Does that sound normal ?

**Comment by jmcollin78** [comment]
Can you please open a new issue, and please fill the issue template with your informations. This issue is closed for more than two years and has been fixed. Many things have change in v8 so it is probably a new bug. Thank you.
