### ISSUE TITLE
_is_aux_heat error

### ISSUE THREAD

**Issue by gioele-antoci** [jmcollin78/versatile_thermostat#89]
## Version of the custom_component

3.2.5

## Debug Log
```
2023-06-24 19:15:19.901 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/versatile_thermostat/climate.py", line 1390, in _async_temperature_changed
    self.recalculate()
  File "/config/custom_components/versatile_thermostat/climate.py", line 2247, in recalculate
    self.update_custom_attributes()
  File "/config/custom_components/versatile_thermostat/climate.py", line 2367, in update_custom_attributes
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 656, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 344, in state_attributes
    data[ATTR_AUX_HEAT] = STATE_ON if self.is_aux_heat else STATE_OFF
                                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/versatile_thermostat/climate.py", line 1038, in is_aux_heat
    return self.underlying_entity(0).is_aux_heat
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UnderlyingClimate' object has no attribute 'is_aux_heat'
```

## Describe the bug
When creating a new thermostat using a climate override I get this error when accessing the custom thermostat. The custom entity thermostat appears unavailable and all sensors are undefined. 
If it can help I am using a heat pump as a heat/cool air source, configured via Midea HACS

**Comment by gioele-antoci** [comment]
The class `[UnderlyingClimate](https://github.com/jmcollin78/versatile_thermostat/blob/e16daa3d53421045d06bc5572aaa3efd1192247b/custom_components/versatile_thermostat/underlyings.py#L376)` does indeed not have such attribute...?

**Comment by jmcollin78** [comment]
Hello, I will fix this rapidly. Thank you for your report.

**Comment by jmcollin78** [comment]
@gioele-antoci because I don't have any auxiliary heater, i was not able to test it on my side.

**Comment by jmcollin78** [comment]
Release have been published: https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.2.6

**Comment by gioele-antoci** [comment]
Release fixed the issue
